routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return redirect()->route('websites.my-websites');
})->middleware(['auth'])->name('dashboard');

Route::namespace('App\Http\Controllers')
    ->middleware(['auth'])->group(function() {
    Route::resource('websites', 'WebsiteController');
    Route::get('/', 'WebsiteController@index');
    Route::get('my-websites', 'WebsiteController@index')->name('websites.my-websites');
});


require __DIR__.'/auth.php';

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Website.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Website extends Model
{
    use HasFactory;

    protected $guarded = ['id', 'created_at', 'updated_at'];

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/WebsiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Models\Website;
use App\Http\Requests\WebsiteRequest;

class WebsiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $websites = Website::all();
        return view('websites.my-websites', compact('websites'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('websites.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WebsiteRequest $request)
    {
        $newWebsite = Website::create($request->all());
        return redirect()->route('websites.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $website = Website::find($id);
        return view('websites.edit', compact('website'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(WebsiteRequest $request, $id)
    {
        $selectedWebsite = Website::find($id);
        $selectedWebsite->update($request->all());
        return redirect()->route('websites.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $selectedWebsite = Website::find($id);
        $selectedWebsite->delete();
        return redirect()->route('websites.index');
    }

    public function getApiData(Request $request){
        try{
            $apiRequest = Http::get($request->url)->throw()->json();

            return response()->json([
                'success' => true
            ]);
        } catch (Exception $e) {
            report($e);
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/config.js') }}"></script>
    <script src="{{ asset('js/jquery-3.6.0.min.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('websites.index') }}">My Websites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('websites.create') }}">Add a Website</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('scripts')
</body>
</html>

resources/views/websites/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add a new Website</div>
                <div class="card-body">
                    <form action="{{ route('websites.store') }}" method="POST">
                        @csrf
                        <div class="">
                            <label class="block text-sm text-gray-00" for="name">Name</label>
                            <input class="form-control rounded" id="name" name="name" type="text" required="" placeholder="Website Name" aria-label="Name">
                        </div>
                        <div class="mt-5">
                            <label class="block text-sm text-gray-600" for="cus_email">Description</label>
                            <textarea class="form-control rounded" name="description"></textarea>
                        </div>
                        <div class="mt-5">
                            <label class="block text-sm text-gray-00" for="link">Website Link</label>
                            <input class="form-control  rounded" id="link" name="link" type="text" required="" placeholder="Website Link" aria-label="Link">
                        </div>
                        <div class="mt-5">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/websites/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit {{ $website->name }}</div>
                <div class="card-body">
                    <form action="{{ route('websites.update', $website->id) }}" method="POST">
                        @csrf
                        @method("PUT")
                        <div class="">
                            <label class="block text-sm text-gray-00" for="name">Name</label>
                            <input class="form-control rounded" id="name" name="name" type="text" required="" value="{{ $website->name }}" placeholder="Website Name" aria-label="Name">
                        </div>
                        <div class="mt-5">
                            <label class="block text-sm text-gray-600" for="cus_email">Description</label>
                            <textarea class="form-control rounded" name="description">{{ $website->description }}</textarea>
                        </div>
                        <div class="mt-5">
                            <label class="block text-sm text-gray-00" for="link">Website Link</label>
                            <input class="form-control  rounded" id="link" name="link" type="text" required="" value="{{ $website->link }}" placeholder="Website Link" aria-label="Link">
                        </div>
                        <div class="mt-5">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                            <form action="{{ route('websites.destroy', $website->id) }}" method="POST">
                                @csrf
                                @method("DELETE")
                                <button type="submit" class="btn btn-danger float-right mr-3">Delete</button>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/websites/my-websites.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="col-md-12">
        <div class="row">
            @foreach ($websites as $website)
                <div class="col-md-4">
                    <div class="card mt-3">
                        <div class="card-header">
                            {{ $website->name }}
                            <div class="float-right">
                                <a href="{{ route('websites.edit', $website->id) }}" class="btn btn-sm btn-secondary">Edit</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row p-3">
                                @if(strpos($website->link, 'https://') !== false || strpos($website->link, 'http://') !== false)
                                    <a href="{{ $website->link }}" target="_blank">{{ $website->link }}</a>
                                @else
                                    <a href="{{ 'https://' . $website->link }}" target="_blank">{{ $website->link }}</a>
                                @endif
                            </div>
                            @if (isset($website->description))
                                <div class="row p-3 website-description">{{ $website->description }}</div>
                            @else
                                <div class="row p-3 website-description"><i>No description provided.</i></div>
                            @endif
                            <div class="row p-3 website-status" data-id="{{ $website->id }}" data-link="{{ $website->link }}">
                                <span class="badge badge-pill badge-info website-status-pill">Connecting...</span>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript">
        function checkWebsites(){
            $.each($('.website-status'), function(index, val){
                let websiteStatusItem = $('.website-status')[index];
                $.get(baseUrl + "/api/get-api-data",{
                    url: $(websiteStatusItem).data('link'),
                }).done(function(){
                    $(websiteStatusItem).html('<span class="badge badge-pill badge-success website-status-pill">Active</span>');
                }).fail(function(result, status){
                    $(websiteStatusItem).html('<span class="badge badge-pill badge-danger website-status-pill">'+status+'</span>');
                });
            });
        }

        checkWebsites();

        setInterval(function(){
            checkWebsites();
        }, 10000);
    </script>
@endsection